# https://gallery.ecr.aws/aws-ec2/helm/aws-node-termination-handler
# https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler#readme
# How to access
# TOKEN=$(curl -k https://public.ecr.aws/token/ | jq -r '.token')
# curl -k -H "Authorization: Bearer $TOKEN" https://public.ecr.aws/v2/aws-ec2/helm/aws-node-termination-handler/tags/list | jq . | head
apiVersion: v2
name: aws-node-termination-handler
version: 1.0.0
dependencies:
  - name: aws-node-termination-handler
    version: 11.14.4
    repository: oci://public.ecr.aws/aws-ec2/helm
